---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: logs/application_services_integration.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    src:
        level: DEBUG
        handlers: [console, file_handler]
    tests:
        level: DEBUG
        handlers: [console, file_handler]
    __main__:
        level: DEBUG
        handlers: [console, file_handler]
    paramiko:
        level: INFO
        handlers: [console, file_handler]
    requests:
        level: DEBUG
        handlers: [console, file_handler]
